name: Maven CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Maven build
        run: mvn -B -U -ff tidy:check com.mycila:license-maven-plugin:check com.github.spotbugs:spotbugs-maven-plugin:check verify

      - name: Setup settings.xml
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: |
            [{
                "id": "nexus-snapshots",
                "username": "${{ secrets.NEXUS_USERNAME }}",
                "password": "${{ secrets.NEXUS_PASSWORD }}"
            }]

      - name: Deploy snapshot
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: mvn -B package javadoc:jar source:jar deploy
