name: Maven CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: FAIRDataTeam/github-workflows/.github/workflows/maven-verify.yml@v3
    with:
      java-version: 21
      mvn-options: '-Dgpg.skip tidy:check com.mycila:license-maven-plugin:check com.github.spotbugs:spotbugs-maven-plugin:check'
      db-type: "mongodb"
      db-version: 8
