name: Maven CI

on:
  - push
  - pull_request
  # enable manual trigger
  - workflow_dispatch

jobs:
  test:
    uses: FAIRDataTeam/github-workflows/.github/workflows/maven-verify.yml@v1
    with:
      mvn_options: 'tidy:check com.mycila:license-maven-plugin:check com.github.spotbugs:spotbugs-maven-plugin:check'
